import { execFileSync } from 'node:child_process'
import type { OracleKind, VerifiabilityLevel } from '../assess/types.js'
import type { TaskType } from '../classify/types.js'
import { loadConfig } from '../config/config.js'
import { readHistory } from '../measure/history.js'
import { computePrecision } from '../measure/learn.js'
import { splitCommand } from '../util/split-command.js'
import type { Verdict } from '../verify/types.js'
import { verify } from '../verify/verify.js'

/** Configuration for an AI model used in orchestration. */
export interface ModelConfig {
  /** The provider type: 'stdio' for local process, 'api' for HTTP API. */
  provider: 'stdio' | 'api'
  /** The model identifier. */
  model: string
  /** Optional API key for API-based providers. */
  apiKey?: string
  /** Optional temperature setting for model generation. */
  temperature?: number
  /** Optional maximum tokens for model output. */
  maxTokens?: number
  /** The command to run for stdio-based providers. */
  command?: string
  /** The API URL for API-based providers. */
  apiUrl?: string
}

/** The result of orchestrating a task with an AI model. */
export interface OrchestrateResult {
  /** The output generated by the model. */
  output: string
  /** The final verification verdict. */
  verdict: Verdict
  /** The number of retries performed. */
  retries: number
}

/**
 * Assemble a prompt string for the AI model from task details and plan.
 *
 * @param task - The task description.
 * @param type - The classified task type.
 * @param level - The assessed verifiability level.
 * @param plan - The run plan with depth, tier, steps, and checks.
 * @param answers - Optional answers from the ask phase.
 * @returns A formatted prompt string.
 */
export function assemblePrompt(
  task: string,
  type: TaskType,
  level: VerifiabilityLevel,
  plan: { depth: string; tier: string; steps: string[]; checks: string[] },
  answers?: Record<string, string>,
): string {
  const parts = [`Task: ${task}`, `Type: ${type}`, `Verifiability level: ${level}`, `Plan depth: ${plan.depth}`, `Model tier: ${plan.tier}`]
  if (answers && Object.keys(answers).length > 0) {
    parts.push(`Answers: ${JSON.stringify(answers)}`)
  }
  return parts.join('\n')
}

/**
 * Call an AI model via stdio by executing a local command and piping the prompt as input.
 *
 * @param command - The command string to execute.
 * @param prompt - The prompt to pipe to the command's stdin.
 * @param timeout - Optional timeout in milliseconds (default 120000).
 * @returns The model's trimmed output.
 * @throws If the command fails or times out.
 */
export function callModelStdio(command: string, prompt: string, timeout = 120_000): string {
  const args = splitCommand(command)
  const cmd = args[0]
  if (!cmd) throw new Error('empty command')
  const result = execFileSync(cmd, args.slice(1), { input: prompt, timeout, encoding: 'utf8' })
  return result.trim()
}

/**
 * Call an AI model via HTTP API using the OpenAI-compatible chat completions format.
 *
 * @param url - The API endpoint URL.
 * @param model - The model identifier.
 * @param prompt - The user prompt to send.
 * @param apiKey - Optional API key for authentication.
 * @param timeout - Optional timeout in milliseconds (default 120000).
 * @returns The model's trimmed response content.
 * @throws If the API request fails or returns a non-JSON response.
 */
export async function callModelApi(url: string, model: string, prompt: string, apiKey?: string, timeout = 120_000): Promise<string> {
  if (!url) throw new Error('model API URL is required — set apiUrl in config or VERIDIA_API_URL env')
  const body = JSON.stringify({ model, messages: [{ role: 'user', content: prompt }] })
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (apiKey) headers.Authorization = `Bearer ${apiKey}`
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeout)
  try {
    let response: Response
    try {
      response = await fetch(url, { method: 'POST', headers, body, signal: controller.signal })
    } catch (err) {
      throw new Error(`model API request failed: ${(err as Error).message}`, { cause: err })
    }
    if (!response.ok) {
      throw new Error(`model API returned HTTP ${response.status} ${response.statusText}`)
    }
    const text = await response.text()
    let data: { choices?: { message?: { content?: string } }[] } = {}
    try {
      data = JSON.parse(text) as typeof data
    } catch {
      throw new Error('model API returned a non-JSON response')
    }
    return data.choices?.[0]?.message?.content?.trim() ?? ''
  } finally {
    clearTimeout(timer)
  }
}

export async function callModelAsync(config: ModelConfig, prompt: string): Promise<string> {
  if (config.provider === 'api') {
    return callModelApi(config.apiUrl ?? '', config.model, prompt, config.apiKey)
  }
  return callModelStdio(config.command ?? config.model, prompt)
}

/**
 * Orchestrate a task by calling an AI model, verifying the output, and retrying on failure.
 *
 * @param task - The task description.
 * @param type - The classified task type.
 * @param level - The assessed verifiability level.
 * @param plan - The run plan with depth, tier, steps, and checks.
 * @param target - The target directory.
 * @param kinds - The oracle kinds to verify against.
 * @param config - The model configuration.
 * @param answers - Optional answers from the ask phase.
 * @param maxRetries - Maximum number of retry attempts (default 3).
 * @returns A promise resolving to an OrchestrateResult with output, verdict, and retry count.
 */
export async function orchestrate(
  task: string,
  type: TaskType,
  level: VerifiabilityLevel,
  plan: { depth: string; tier: string; steps: string[]; checks: string[] },
  target: string,
  kinds: OracleKind[],
  config: ModelConfig,
  answers?: Record<string, string>,
  maxRetries = 3,
): Promise<OrchestrateResult> {
  const prompt = assemblePrompt(task, type, level, plan, answers)
  let lastOutput = ''

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    let output: string
    try {
      const feedback = attempt > 0 ? `\n\nPrevious attempt failed. Fix the issues and try again.\n${lastOutput}` : ''
      output = await callModelAsync(config, prompt + feedback)
    } catch (err) {
      lastOutput = `model call failed: ${(err as Error).message}`
      continue
    }
    lastOutput = output

    const precision = computePrecision(readHistory({ root: target }))
    const weights = loadConfig(target).weights
    const verifyResult = verify(target, level, kinds, { precision, weights })
    if (verifyResult.verdict === 'PASS') {
      return { output, verdict: 'PASS', retries: attempt }
    }
  }

  return { output: lastOutput, verdict: 'FAIL', retries: maxRetries }
}
